//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class PaperInfo
    {
        public int PaperId { get; set; }
        [Required]
        public string PaperTitle { get; set; }
        [Required]
        public string PaperAbstract { get; set; }
        public string PaperAuthor { get; set; }
        public Nullable<System.DateTime> PaperDateSubmitted { get; set; }
        public Nullable<int> TopicId { get; set; }
        public virtual TopicInfo TopicInfo { get; set; }
        public List<SelectListItem> SelectedTopic { get; set; }
    }
}
