//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geolocation
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Geolocation1 { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
    }
}
